// <auto-generated />
namespace PentaStagione.Repository.EntityFramwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RedesingedModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RedesingedModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201705102152370_RedesingedModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
